name: Deploy

on:
  push:
    paths:
    - 'news.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run deploy
        env:
          SFTP_HOST: ${{secrets.SFTP_HOST}}
          SFTP_PASS: ${{secrets.SFTP_PASS}}
          SFTP_PORT: ${{secrets.SFTP_PORT}}
          SFTP_USER: ${{secrets.SFTP_USER}}
